==2146== HEAP SUMMARY:
==2146==     in use at exit: 6,256,649 bytes in 3,856 blocks
==2146==   total heap usage: 56,471 allocs, 52,630 frees, 120,775,806 bytes allocated
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 341 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x5151ED: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x540D9E: ??? (in /usr/bin/python3.9)
==2146==    by 0x54ECCC: _PyCodec_Lookup (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 342 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x532EF5: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AABE: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x51484D: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 343 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5391E9: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x54D373: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A366: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AB82: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x54D210: PyObject_CallFunction (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 344 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 345 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 346 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x4F8598: PyTuple_New (in /usr/bin/python3.9)
==2146==    by 0x50B3B7: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4FB: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B405: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4FB: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x6127F7: ??? (in /usr/bin/python3.9)
==2146==    by 0x563CA0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 347 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 520 bytes in 1 blocks are possibly lost in loss record 348 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 351 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536EB3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51C6D1: ??? (in /usr/bin/python3.9)
==2146==    by 0x56FF26: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A366: ??? (in /usr/bin/python3.9)
==2146==    by 0x5375D8: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 352 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 353 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x518ADB: ??? (in /usr/bin/python3.9)
==2146==    by 0x51876B: ??? (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 354 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 355 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 356 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x58FF90: ??? (in /usr/bin/python3.9)
==2146==    by 0x50FC91: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 357 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x59E69F2: ??? (in /usr/lib/python3/dist-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so)
==2146==    by 0x53A38F: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AB82: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x51484D: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 528 bytes in 1 blocks are possibly lost in loss record 358 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 359 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5397CE: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x511E3C: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 360 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x540D9E: ??? (in /usr/bin/python3.9)
==2146==    by 0x54ECCC: _PyCodec_Lookup (in /usr/bin/python3.9)
==2146==    by 0x617563: ??? (in /usr/bin/python3.9)
==2146==    by 0x614E36: ??? (in /usr/bin/python3.9)
==2146==    by 0x6148AD: ??? (in /usr/bin/python3.9)
==2146==    by 0x60A164: Py_InitializeFromConfig (in /usr/bin/python3.9)
==2146==    by 0x608CBD: ??? (in /usr/bin/python3.9)
==2146==    by 0x608C10: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 361 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5397CE: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x511E3C: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 362 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x518ADB: ??? (in /usr/bin/python3.9)
==2146==    by 0x51876B: ??? (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 363 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 364 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 365 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 536 bytes in 1 blocks are possibly lost in loss record 366 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 544 bytes in 1 blocks are possibly lost in loss record 367 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x537571: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5115E7: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 552 bytes in 1 blocks are possibly lost in loss record 371 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 552 bytes in 1 blocks are possibly lost in loss record 372 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 552 bytes in 1 blocks are possibly lost in loss record 373 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x537571: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5115E7: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 552 bytes in 1 blocks are possibly lost in loss record 374 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 560 bytes in 1 blocks are possibly lost in loss record 376 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 560 bytes in 1 blocks are possibly lost in loss record 377 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 568 bytes in 1 blocks are possibly lost in loss record 380 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 568 bytes in 1 blocks are possibly lost in loss record 381 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 576 bytes in 1 blocks are possibly lost in loss record 549 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 576 bytes in 1 blocks are possibly lost in loss record 550 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 576 bytes in 1 blocks are possibly lost in loss record 551 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 576 bytes in 1 blocks are possibly lost in loss record 552 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 576 bytes in 1 blocks are possibly lost in loss record 553 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x629BC6: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 592 bytes in 1 blocks are possibly lost in loss record 555 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 616 bytes in 1 blocks are possibly lost in loss record 559 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x5151ED: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F951: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x51484D: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 624 bytes in 1 blocks are possibly lost in loss record 562 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x532F95: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AABE: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x5151ED: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 632 bytes in 1 blocks are possibly lost in loss record 563 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x51A351: _PyObject_FastCallDictTstate (in /usr/bin/python3.9)
==2146==    by 0x533AB8: _PyObject_Call_Prepend (in /usr/bin/python3.9)
==2146==    by 0x5BAAE2: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AB82: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146== 
==2146== 632 bytes in 1 blocks are possibly lost in loss record 564 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 640 bytes in 1 blocks are possibly lost in loss record 566 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 672 bytes in 1 blocks are possibly lost in loss record 573 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 672 bytes in 1 blocks are possibly lost in loss record 574 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 672 bytes in 1 blocks are possibly lost in loss record 575 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 712 bytes in 1 blocks are possibly lost in loss record 577 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F951: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x518FEE: ??? (in /usr/bin/python3.9)
==2146==    by 0x51876B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 720 bytes in 1 blocks are possibly lost in loss record 579 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146==    by 0x526499: ??? (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 840 bytes in 1 blocks are possibly lost in loss record 585 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x50EE21: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,040 bytes in 2 blocks are possibly lost in loss record 734 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5391E9: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x54D373: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A366: ??? (in /usr/bin/python3.9)
==2146==    by 0x5375D8: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5153AA: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,048 bytes in 2 blocks are possibly lost in loss record 735 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x536D9B: ??? (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 1,066 bytes in 1 blocks are possibly lost in loss record 736 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x50C71B: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AB5C: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4D5: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x6127F7: ??? (in /usr/bin/python3.9)
==2146==    by 0x563CA0: ??? (in /usr/bin/python3.9)
==2146==    by 0x524DBC: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,072 bytes in 2 blocks are possibly lost in loss record 737 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x510C2A: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x532F95: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AABE: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146==    by 0x5151ED: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 1,232 bytes in 2 blocks are possibly lost in loss record 865 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AFF0: ??? (in /usr/bin/python3.9)
==2146==    by 0x5375D8: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5115E7: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F951: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146== 
==2146== 1,232 bytes in 2 blocks are possibly lost in loss record 866 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AFF0: ??? (in /usr/bin/python3.9)
==2146==    by 0x5375D8: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5115E7: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AA64: _PyObject_MakeTpCall (in /usr/bin/python3.9)
==2146== 
==2146== 1,344 bytes in 2 blocks are possibly lost in loss record 873 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,344 bytes in 2 blocks are possibly lost in loss record 874 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,680 bytes in 2 blocks are possibly lost in loss record 886 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146== 
==2146== 1,848 bytes in 3 blocks are possibly lost in loss record 892 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x50EC78: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AFF0: ??? (in /usr/bin/python3.9)
==2146==    by 0x5375D8: PyObject_Call (in /usr/bin/python3.9)
==2146==    by 0x5115E7: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x56F9F3: ??? (in /usr/bin/python3.9)
==2146==    by 0x51AFF0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 2,688 bytes in 4 blocks are possibly lost in loss record 950 of 1,065
==2146==    at 0x484482F: realloc (vg_replace_malloc.c:1437)
==2146==    by 0x54B9FA: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146== 
==2146== 2,848 bytes in 5 blocks are possibly lost in loss record 954 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x4F8598: PyTuple_New (in /usr/bin/python3.9)
==2146==    by 0x50B3B7: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFDA: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4FB: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4FB: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x6127F7: ??? (in /usr/bin/python3.9)
==2146==    by 0x563CA0: ??? (in /usr/bin/python3.9)
==2146==    by 0x524DBC: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 3,640 bytes in 7 blocks are possibly lost in loss record 967 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F177C: ??? (in /usr/bin/python3.9)
==2146==    by 0x54B9A2: _PyObject_GC_Resize (in /usr/bin/python3.9)
==2146==    by 0x525E30: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5391E9: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x511E3C: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146== 
==2146== 4,680 bytes in 9 blocks are possibly lost in loss record 992 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F14DC: ??? (in /usr/bin/python3.9)
==2146==    by 0x525D34: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x525912: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x5250B5: ??? (in /usr/bin/python3.9)
==2146==    by 0x53A4C3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.9)
==2146==    by 0x5391E9: PyImport_ImportModuleLevelObject (in /usr/bin/python3.9)
==2146==    by 0x511E3C: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146== 
==2146== 38,316 bytes in 19 blocks are possibly lost in loss record 1,042 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x50C71B: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AB5C: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B3E1: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x50B4FB: ??? (in /usr/bin/python3.9)
==2146==    by 0x50AFC4: ??? (in /usr/bin/python3.9)
==2146==    by 0x6127F7: ??? (in /usr/bin/python3.9)
==2146==    by 0x563CA0: ??? (in /usr/bin/python3.9)
==2146==    by 0x524DBC: ??? (in /usr/bin/python3.9)
==2146==    by 0x514653: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146== 
==2146== 135,438 bytes in 68 blocks are possibly lost in loss record 1,058 of 1,065
==2146==    at 0x483F7B5: malloc (vg_replace_malloc.c:381)
==2146==    by 0x4F34D2: PyUnicode_New (in /usr/bin/python3.9)
==2146==    by 0x5549F9: PyUnicode_Substring (in /usr/bin/python3.9)
==2146==    by 0x538010: ??? (in /usr/bin/python3.9)
==2146==    by 0x50F8FE: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x525B3A: _PyFunction_Vectorcall (in /usr/bin/python3.9)
==2146==    by 0x50F71E: _PyEval_EvalFrameDefault (in /usr/bin/python3.9)
==2146==    by 0x50DEB0: ??? (in /usr/bin/python3.9)
==2146==    by 0x50DC26: _PyEval_EvalCodeWithName (in /usr/bin/python3.9)
==2146==    by 0x50DBD2: PyEval_EvalCode (in /usr/bin/python3.9)
==2146==    by 0x5423EF: ??? (in /usr/bin/python3.9)
==2146== 
==2146== LEAK SUMMARY:
==2146==    definitely lost: 0 bytes in 0 blocks
==2146==    indirectly lost: 0 bytes in 0 blocks
==2146==      possibly lost: 229,100 bytes in 182 blocks
==2146==    still reachable: 6,027,549 bytes in 3,674 blocks
==2146==         suppressed: 0 bytes in 0 blocks
==2146== Reachable blocks (those to which a pointer was found) are not shown.
==2146== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2146== 
==2146== Use --track-origins=yes to see where uninitialised values come from
==2146== For lists of detected and suppressed errors, rerun with: -s
==2146== ERROR SUMMARY: 35887 errors from 336 contexts (suppressed: 0 from 0)
